N_SAMPLE_SEEDS = 50
N_AGG_SEEDS = 1
ROOT_DIR = '/scratch3/workspace/pboddavarama_umass_edu-sbice'
REPOSITORY_DIR = f'{ROOT_DIR}/realcause'
BASE_DATASETS_FOLDER = f'{ROOT_DIR}/datasets' # For the base datasets that are being used
CAUSL_DATASETS_FOLDER = f'{ROOT_DIR}/r-data-gen/datasets' # Datasets generated by `causl` library in R
REALCAUSE_DATASETS_FOLDER = f'{BASE_DATASETS_FOLDER}/realcause_datasets' # For the datasets that were used by the original authors of the RealCause repository