"""Test script to combine both realcause and frugalflows simulator
into a single dataframe."""

import argparse
import logging
import os

import jax
import jax.random as jr
import jax.numpy as jnp
jax.config.update('jax_enable_x64', True)

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pyabc
import seaborn as sns
import yaml

from data_loaders import lalonde
from ff_data_loaders import lalonde as ff_lalonde
from sbi import simulator
from frugal_flows.benchmarking import FrugalFlowModel

# Define logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

SEED = 746

obs_data, obs_data_info = ff_lalonde.load_lalonde('psid1')
logger.info(obs_data.head())
logger.info(obs_data_info)

outcome_col = obs_data_info['outcome_col']
treatment_col = obs_data_info['treatment_col']

X = jnp.array(obs_data[treatment_col].values, dtype=jnp.float64)[:, None]
Y = jnp.array(obs_data[outcome_col].values, dtype=jnp.float64)[:, None]
Z_disc = jnp.array(obs_data[obs_data_info['categorical_vars']].values, dtype=jnp.float64)
Z_cont = jnp.array(obs_data[obs_data_info['continuous_vars'][:-1]].values, dtype=jnp.float64)

# Need to ensure that the columns follow the column ordering later generated by the simulator
column_order = [
    're78',
    'treat',
    'age',
    'education',
    're75',
    're74',
    'black',
    'hispanic',
    'married',
    'nodegree'
]
obs_data = obs_data[column_order]

observed = {
    'data_np': obs_data.values,
    'data_pd': obs_data,
    't': obs_data['treat'].values,
    'y': obs_data['re78'].values
}

# FIXME: This code exists to work with the old distance functions; remove this later
obs_data_dict = obs_data.to_dict(orient='list')
obs_data_dict['t'] = obs_data_dict.pop('treat')
obs_data_dict['y'] = obs_data_dict.pop('re78')

sample_size = obs_data.shape[0]

logger.info(f'Sample size: {sample_size}')
logger.info(f'X: {X}')
logger.info(f'Y: {Y}')
logger.info(f'Z_disc: {Z_disc}')
logger.info(f'Z_cont: {Z_cont}')

# Train the frugal flow model with the hyperparameters specified in the config
trained_ff_model = FrugalFlowModel(X=X,
                                    Y=Y,
                                    Z_disc=Z_disc,
                                    Z_cont=Z_cont,
                                    confounding_copula=None)

tuned_hyperparams = {
    'hyperparameters': {
        'RQS_knots': 4,
        'flow_layers': 9,
        'learning_rate': 0.006335,
        'nn_depth': 10,
        'nn_width': 50
    },
    'cm_hyperparameters': {
        'RQS_knots': 4,
        'flow_layers': 8,
        'nn_depth': 10,
        'nn_width': 50
    },
    'ate': -0.9680,
    'seed': 48
}

# Set tuning parameters for Normalizing Flows
max_patience = 1    # Default is 200
max_epochs = 1    # Default is 10000
tuned_hyperparams['hyperparameters']['max_patience'] = max_patience
tuned_hyperparams['hyperparameters']['max_epochs'] = max_epochs

trained_ff_model.train_benchmark_model(
            training_seed=jr.PRNGKey(SEED),
            marginal_hyperparam_dict=tuned_hyperparams['hyperparameters'],
            frugal_hyperparam_dict=tuned_hyperparams['hyperparameters'],
            causal_model='location_translation',
            causal_model_args={
                'ate': tuned_hyperparams['ate'], **tuned_hyperparams['cm_hyperparameters']
            },
            prop_flow_hyperparam_dict=tuned_hyperparams['hyperparameters'],
        )
        # Print out the causal margin obtained after training the FF model
learned_causal_margin = trained_ff_model.frugal_flow.bijection.bijections[-1].bijections[
    0].ate
logger.info(f'Learned causal margin: {learned_causal_margin}')