"""Script to tune the Frugal Flow models."""

# Import libraries
import jax
import jax.numpy as jnp
import jax.random as jr
import numpy as np
from scipy.stats import rankdata

import wandb
from frugal_flows.causal_flows import (get_independent_quantiles, train_frugal_flow)


def calculate_ecdf(Z):
    """
    Calculate the empirical cumulative distribution function (ECDF) for each column of the input array.

    Parameters:
    Z (ndarray): The input array of shape (n_samples, n_features).

    Returns:
    ndarray: The ECDF values for each column of the input array, with shape (n_samples, n_features).

    """
    ecdf_transforms = []
    for d in range(Z.shape[1]):
        data = np.concatenate([Z[:, d], [np.inf, -np.inf]])
        ecdf_values = rankdata(data, method='average') / len(data)
        ecdf_transforms.append(ecdf_values[:-2])
    return jnp.vstack(ecdf_transforms).T


def generate_uz_samples(Z_disc=None,
                        Z_cont=None,
                        use_marginal_flow=False,
                        seed=0,
                        frugal_flow_hyperparams={}):
    """
    Generates the uz_samples for frugal fitting.

    Args:
        Z_disc (array-like, optional): The discrete pretreatment covariates. Defaults to None.
        Z_cont (array-like, optional): The continuous pretreatment covariates. Defaults to None.
        use_marginal_flow (boolean): If true, the quantiles will be learned by fitting a set
            of independent univariate flows to the Z_cont variables. Otherwise, an empirical
            CDF will be calculated.
        seed (int, optional): The random seed. Defaults to 0.
        frugal_flow_hyperparams (dict, optional): Hyperparameters for training the frugal flow model. Defaults to {}.

    Returns:
        dict: A dictionary containing the uz_samples.
    """
    key = jr.PRNGKey(seed)
    key, *subkeys = jax.random.split(key, num=3)

    uz_disc_samples = None
    uz_cont_samples = None
    if Z_disc is None and Z_cont is None:
        print('Warning: No pretreatment covariates provided')
    elif Z_disc is None:
        if use_marginal_flow:
            cont_marg_flow = get_independent_quantiles(key=subkeys[0],
                                                       z_cont=Z_cont,
                                                       **frugal_flow_hyperparams)
            uz_cont_samples = cont_marg_flow['u_z_cont']
        else:
            uz_cont_samples = calculate_ecdf(Z_cont)
    elif Z_cont is None:
        marg_flow = get_independent_quantiles(key=subkeys[0], z_discr=Z_disc)
        uz_disc_samples = marg_flow['u_z_discr']
    else:
        if use_marginal_flow:
            cont_marg_flow = get_independent_quantiles(key=subkeys[0],
                                                       z_cont=Z_cont,
                                                       **frugal_flow_hyperparams)
            uz_cont_samples = cont_marg_flow['u_z_cont']
        else:
            uz_cont_samples = calculate_ecdf(Z_cont)
        disc_marg_flow = get_independent_quantiles(key=subkeys[0], z_discr=Z_disc)
        uz_disc_samples = disc_marg_flow['u_z_discr']
    if uz_disc_samples == None:
        uz_samples = uz_cont_samples
    elif uz_cont_samples == None:
        uz_samples = uz_disc_samples
    else:
        uz_samples = jnp.hstack([uz_disc_samples, uz_cont_samples])
    return {'uz_disc': uz_disc_samples, 'uz_cont': uz_cont_samples, 'uz_samples': uz_samples}


def frugal_fitting(X,
                   Y,
                   use_marginal_flow=False,
                   Z_disc=None,
                   Z_cont=None,
                   seed=0,
                   frugal_flow_hyperparams={},
                   causal_model=None,
                   causal_model_args={}):
    """
    Fits a frugal flow model to the given data.

    Args:
        X (array-like): The treatment variable.
        Y (array-like): The outcome variable.
        uz_samples (dict): A dictionary containing the uz_samples generated by generate_uz_samples.
        seed (int, optional): The random seed. Defaults to 0.
        frugal_flow_hyperparams (dict, optional): Hyperparameters for training the frugal flow model. Defaults to {}.

    Returns:
        dict: A dictionary containing the frugal flow model, the causal margin, and the pretreatment covariate samples.
    """
    key = jr.PRNGKey(seed)
    key, *subkeys = jax.random.split(key, num=3)
    uz_samples = generate_uz_samples(Z_disc,
                                     Z_cont,
                                     use_marginal_flow,
                                     seed,
                                     frugal_flow_hyperparams)
    print('UZ samples have been generated!')
    uz_disc_samples = uz_samples['uz_disc']
    uz_cont_samples = uz_samples['uz_cont']
    print('Starting to train the frugal flow for the causal margin...')
    # Learn Frugal Flow
    frugal_flow, losses = train_frugal_flow(key=subkeys[1],
                                            y=Y,
                                            u_z=uz_samples['uz_samples'],
                                            condition=X,
                                            **frugal_flow_hyperparams,
                                            causal_model=causal_model,
                                            causal_model_args=causal_model_args)
    print('Frugal flow model trained, printing the causal margin after training')
    causal_margin = None
    if causal_model == 'location_translation':
        causal_margin = frugal_flow.bijection.bijections[-1].bijections[0].ate
    elif causal_model == 'gaussian':
        gaussian_params = frugal_flow.bijection.bijections[-1].bijection.bijections[0]
        causal_margin = gaussian_params.ate[0]
        print(f'Const: {gaussian_params.const}, Scale: {gaussian_params.scale}')
    else:
        raise ValueError('Causal model not recognized, unable to extract causal margin')
    print(f'Causal margin after training: {causal_margin}')
    min_loss = jnp.min(jnp.array(losses['val']))
    output = {
        'frugal_flow': frugal_flow,
        'losses': losses,
        'causal_margin': causal_margin,
        'uz_disc': uz_disc_samples,
        'uz_cont': uz_cont_samples,
        'val_loss': min_loss,
    }
    print(f'Logging the validation loss, {min_loss}')
    wandb.log(data={'val_loss': min_loss})
    return output, min_loss
