experiment_fp1:  # all parameters for both models; distance sliced wass
  dataset_name: frugalparam
  dataset_identifier: dgp3
  sample_size: None
  random_seed: 89
  realcause_parameters:
    - te
    - deg_hetero
    - overlap
  realcause_prior:
    te:
      distribution: uniform
      loc: -10.0
      scale: 20.0
    deg_hetero:
      distribution: uniform
      loc: 0.0
      scale: 1.0
    overlap:
      distribution: uniform
      loc: 0.0
      scale: 1.0
  frugalflows_parameters:
    - ate
    - rho
  frugalflows_prior:
    ate:
      distribution: uniform
      loc: -10.0
      scale: 20.0
    rho:
      distribution: uniform
      loc: -1.0
      scale: 2.0
  distance: sliced_wass
  transform: false
  min_epsilon: 0.01
  max_iterations: 12
  acceptance_population: 50
  causal_model: location_translation
  realcause_model_path: results/realcause_models/frugalparam_dgp3_None
  frugalflows_hp_file: results/frugalflows_models/frugalparam_dgp3_None_hps.yaml
