experiment_100: # ATE only for both models
  dataset_name: lalonde
  dataset_identifier: psid1
  sample_size: None
  random_seed: 88
  realcause_parameters:
    - te
  realcause_prior:
    te:
      distribution: uniform
      loc: -5.0
      scale: 10.0
  frugalflows_parameters:
    - ate
  frugalflows_prior:
    ate:
      distribution: uniform
      loc: -5.0
      scale: 10.0
  distance: sliced_wass
  transform: true
  min_epsilon: 0.01
  max_iterations: 20
  causal_model: location_translation
  realcause_model_path: results/GenModelCkpts/lalonde/psid1/save
  frugalflows_hp_file: results/frugalflows_models/lalonde_psid1_None_hps.yaml

experiment_101:    # This was done to check whether the correct models were being picked out despite order
  dataset_name: lalonde
  dataset_identifier: psid1
  sample_size: None
  random_seed: 88
  realcause_parameters:
    - te
  realcause_prior:
    te:
      distribution: uniform
      loc: -5.0
      scale: 10.0
  frugalflows_parameters:
    - ate
  frugalflows_prior:
    ate:
      distribution: uniform
      loc: -5.0
      scale: 10.0
  distance: sliced_wass
  transform: true
  min_epsilon: 0.01
  max_iterations: 13
  causal_model: location_translation
  realcause_model_path: results/GenModelCkpts/lalonde/psid1/save
  frugalflows_hp_file: results/frugalflows_models/lalonde_psid1_None_hps.yaml

experiment_102:  # all parameters for both models
  dataset_name: lalonde
  dataset_identifier: psid1
  sample_size: None
  random_seed: 88
  realcause_parameters:
    - te
    - deg_hetero
    - overlap
  realcause_prior:
    te:
      distribution: uniform
      loc: -5.0
      scale: 10.0
    deg_hetero:
      distribution: uniform
      loc: 0.0
      scale: 1.0
    overlap:
      distribution: uniform
      loc: 0.0
      scale: 1.0
  frugalflows_parameters:
    - ate
    - rho
  frugalflows_prior:
    ate:
      distribution: uniform
      loc: -5.0
      scale: 10.0
    rho:
      distribution: uniform
      loc: -1.0
      scale: 2.0
  distance: sliced_wass
  transform: true
  min_epsilon: 0.001
  max_iterations: 13
  causal_model: location_translation
  realcause_model_path: results/GenModelCkpts/lalonde/psid1/save
  frugalflows_hp_file: results/frugalflows_models/lalonde_psid1_None_hps.yaml

experiment_103:  # all parameters for both models; distance only t and y
  dataset_name: lalonde
  dataset_identifier: psid1
  sample_size: None
  random_seed: 88
  realcause_parameters:
    - te
    - deg_hetero
    - overlap
  realcause_prior:
    te:
      distribution: uniform
      loc: -5.0
      scale: 10.0
    deg_hetero:
      distribution: uniform
      loc: 0.0
      scale: 1.0
    overlap:
      distribution: uniform
      loc: 0.0
      scale: 1.0
  frugalflows_parameters:
    - ate
    - rho
  frugalflows_prior:
    ate:
      distribution: uniform
      loc: -5.0
      scale: 10.0
    rho:
      distribution: uniform
      loc: -1.0
      scale: 2.0
  distance: ty_sliced_wass
  transform: true
  min_epsilon: 0.001
  max_iterations: 13
  causal_model: location_translation
  realcause_model_path: results/GenModelCkpts/lalonde/psid1/save
  frugalflows_hp_file: results/frugalflows_models/lalonde_psid1_None_hps.yaml

experiment_104: # all parameters; narrow prior; distance = mmd
  dataset_name: lalonde
  dataset_identifier: psid1
  sample_size: None
  random_seed: 847
  realcause_parameters:
    - te
    - deg_hetero
    - overlap
  realcause_prior:
    te:   # narrow prior
      distribution: uniform
      loc: -1.0
      scale: 2.0
    deg_hetero:
      distribution: uniform
      loc: 0.0
      scale: 1.0
    overlap:
      distribution: uniform
      loc: 0.0
      scale: 1.0
  frugalflows_parameters:
    - ate
    - rho
  frugalflows_prior:
    ate:
      distribution: uniform
      loc: -1.0
      scale: 2.0
    rho:
      distribution: uniform
      loc: -1.0
      scale: 2.0
  distance: mmd
  transform: true
  min_epsilon: 0.001
  max_iterations: 13
  causal_model: location_translation
  realcause_model_path: results/GenModelCkpts/lalonde/psid1/save
  frugalflows_hp_file: results/frugalflows_models/lalonde_psid1_None_hps.yaml
