experiment_200: 
  dataset_name: lalonde
  dataset_identifier: cps1
  sample_size: None
  random_seed: 40
  realcause_parameters:
    - te
  realcause_prior:
    te:
      distribution: uniform
      loc: -5.0
      scale: 10.0
  frugalflows_parameters:
    - ate
  frugalflows_prior:
    ate:
      distribution: uniform
      loc: -5.0
      scale: 10.0
  distance: sliced_wass
  transform: true
  min_epsilon: 0.01
  max_iterations: 12    
  causal_model: location_translation
  realcause_model_path: results/GenModelCkpts/lalonde/cps1/dist_argsndim=32+base_distribution=normal-n_hidden_layers2-dim_h64-lr0.001-w_transformStandardize
  frugalflows_hp_file: results/frugalflows_models/lalonde_cps1_None_hps.yaml